### PR TITLE
added fonts and made the component's usage simpler

### PR DESCRIPTION
**Pull request by ghost**
I added an easy way to add fonts to the editor and made possible the usage of the component in a more Blazor-ish way through the Toolbar parameter and the internal ToolbarContentComp component. See the readme or the Index.razor file of the Blazor Server app for reference.

### CODE REVIEW

**Comment by ADefWebserver** [comment]
Ok I had a chance to look this over more carefully and I can now see a path where it will not break an exiting implementation. 

However, I am still not comfortable with ToolbarContentComp.razor. For me, this pushes a concrete implementation of Quilljs's fonts to the Blazor control code. Quilljs can change in the future.  

The primary concern is to not break any exiting implementation of the Blazor TextEditor if someone blindly updates all their Nuget packages in their project. While this current implementation does not do that, it goes in a direction I want to avoid.

I appreciate your generous PR, but, it goers in a direction I don't want to take this control.

Thank You

**Comment by somegenericdev** [comment]
I finished cleaning up the code and released the Nuget package on nuget.org, this should be it. https://github.com/somegenericdev/TextEditor/

**Comment by somegenericdev** [comment]
The location of the repository changed to https://github.com/somegenericdev/WYSIWYGTextEditor, you might want to change the link in the README file.

**Comment by ADefWebserver** [comment]
done

**Pull request closed without merging**
