### PR TITLE
Added bind value support

### PR DESCRIPTION
**Pull request by dustout**
Added support for bind-value. This allows the editor to work closer to the way InputText and the other form components work

### CODE REVIEW

**Comment by ADefWebserver** [comment]
Good work, your code looks great.

However, I'm sorry but I can't accept this pull request.

The reason is that I do not believe it is  a good thing to marshal data from the Quill JavaScript component to the Blazor app on each quill.on('text-change'... 

- Many people have several instances of the TextEditor on a .razor page and their app would take a serious performance hit when users start typing a novel and there are other elements on the page
- The TextEditor can fulfill all requirements for loading and retrieving Quill contents without keystroke level binding 

Thank You!

**Comment by dustout** [comment]
I agree that when users are typing a novel it would have a performance hit, but most users are just typing a comment and this change makes that flow work pretty smoothly. 

Thanks anyways, and also big thanks for the blazored tools in general, your modal is leagues above the other blazor modals!

**Comment by dustout** [comment]
In case you change your mind I just pushed a bug fix where the bind was not properly setting the value

https://github.com/dustout/TextEditor/commit/9b8d297fe0c00298f0c00b011ec8ed0acc4a8727

**Comment by ADefWebserver** [comment]
@dustout You can fork the code and release your own version. Just use a different name for your project. Thanks!

**Comment by axedaddy** [comment]
Check out my (rejected) repo https://github.com/Blazored/TextEditor/pull/66.
It binds the value when the quill editor looses focus (onBlur). 
Extensively tested, however there are 2 outstanding issues.

1. If the onBlur function doesn't exist as a JSInterop in c#, then the call from js logs an error.  I would have liked a way to check if the function exists before calling but was unable to find a solution.
2. The initial load of Html into Quill throws an exception first time.  2nd time is OK.  I was unable to determine the cause of this. 

I added a sample project which demonstrates it usage.

**Comment by ADefWebserver** [comment]
@axedaddy - .Net 8 changes the way things are rendered. It may be possible to resolve these issues with .Net 8. It may be possible to resolve these issues by turning of [prerendering](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#prerendering) or setting [static rendering mode](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#static-render-mode).

**Pull request closed without merging**
